baseURL = "https://thisisgvrt.me"
languageCode = "en-us"
title = "Hello ! I am Raviteja."
theme = "hermit"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = false  # If there're Chinese/Japanese/Korean Languages in the content, enable this.
rssLimit = 5  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# googleAnalytics = "UA-123-45"
# disqusShortname = ""

[author]
  name = "Raviteja Guttula"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag = "tags"
  category = ""  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#ffffff"  # Theme color in meta tags.
  homeSubtitle = "I love building things. I also love to run, cook and listen to some music."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  justifyContent = false  # Set "text-align: justify" to .content, requires extended version of Hugo
  # bgImg = ""  #  Homepage background-image URL

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/thisisgvrt"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/thisisgvrt"

  [[params.social]]
    name = "github"
    url = "https://github.com/thisisgvrt"

  [[params.social]]
    name = "linkedin"
    url = "http://linkedin.com/in/thisisgvrt"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "/about-me/"
    weight = 20